name: CI with Maven

on: 
 push:
  branches: [ 'main', 'master' ]

jobs:
  
  testing:
    runs-on: ubuntu-latest
    container: crowdar/lippia:3.1.2.2
    env: 
      TAG: "@Success"
      TESTTYPE: "Secuencial"
      LANG: "@EN"
    
    steps:
    - uses: actions/checkout@v3
    - run: echo $TAG,
                $TESTTYPE,
                $LANG
    - run: mvn test -P$TESTTYPE -Dcrowdar.cucumber.filter="'$TAG'" -Dcrowdar.cucumber.filter.language="'$LANG'"
    - uses: actions/upload-artifact@v3
      with:
        path: target/extent-reports/
        
            
    
      
    
