name: Test
on:
  push:
    branches: [ main , master]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: crowdar/lippia:3.1.2.2
      env:
        TAG: "@Success"
        TESTTYPE: "Secuencial"
        LANG: "@EN"
    steps:
      - name: Build
        uses: comchangs/action-maven@v0.4-beta
      - name: Check
        run: mvn test -P$TESTTYPE -Dcrowdar.cucumber.filter="'$TAG'" -Dcrowdar.cucumber.filter.language="'$LANG'"
