name: crowdar/lippia:3.1.2.2 #Java CI with Maven

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" , "master" ]


jobs:
  testing:
    runs-on: ubuntu-latest
    container: crowdar/lippia:3.1.2.2
    if: contains( github.ref, 'main') || contains( github.ref, 'master')
    steps:
    - uses: actions/checkout@v3
    - name: Test with Maven
      run: mvn test -P$TESTTYPE -Dcrowdar.cucumber.filter="'$TAG'" -Dcrowdar.cucumber.filter.language="'$LANG'"
      env: 
        TAG: "@Success"
        TESTTYPE: "Secuencial"
        LANG: "@EN"

