name: Java CI with Maven

on: workflow_dispatch
 # push:
  #  branches: [ '**' ]

jobs:
    
  testing:
    runs-on: ubuntu-latest
    container: crowdar/lippia:3.1.2.2
    if: contains( github.ref, 'main')||contains( github.ref, 'master')
    env: 
      TAG: "@Success"
      TESTTYPE: "Secuencial"
      LANG: "@EN"  
    steps:
    - uses: actions/checkout@v3
    - run: echo $TAG, $TESTTYPE, $LANG
    - run: mvn test -P$TESTTYPE -Dcrowdar.cucumber.filter="'$TAG'" -Dcrowdar.cucumber.filter.language="'$LANG'"
    - uses: actions/upload-artifact@v3
      with:
        path: target/extent-reports/
